joint:
  names: [joint1, joint2, joint3, joint4]
motion:
  names: [motion1, motion2, motion3]
  motion1:
    step: [0.0, 0.0, 0.0, 0.0]  # radian
    time_from_start: 2.0  # sec
  motion2:
    step: [0.0, 0.0, 0.0, 0.0]
    time_from_start: 3.0
  motion3:
    step: [0.0, 0.0, 0.0, 0.0]
    time_from_start: 6.0

