joint:
  names: [joint1, joint2, joint3, joint4]
motion:
  names: [initialization1, initialization2, initialization3]
  initialization1:
    step: [0.0, 0.0, 0.0, 0.0]  # radian
    time_from_start: 2.0  # sec
  initialization2:
    step: [0.68, -0.47, -0.42, -0.89]
    time_from_start: 3.0
  initialization3:
    step: [0.0, 0.0, 0.0, 0.0]
    time_from_start: 4.0

