joint:
  names: [joint1, joint2, joint3, joint4]
motion:
  names: [motion1, motion2, motion3,motion4]
  motion1:
    step: [0.68, -0.47, -0.42, 0.89]  # radian
    time_from_start: 2.0  # sec
  motion2:
    step: [0.0, 0.0, 0.0, 0.0]
    time_from_start: 4.0
  motion3:
    step: [0.68, -0.47, -0.42, 0.89]
    time_from_start: 5.0
  motion4:
    step: [0.0, 0.0, 0.0, 0.0]
    time_from_start: 6.0

